name: Deploy Frontend
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run testcases
      - uses: actions/checkout@v2
      - run: docker build -t amsha30/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true amsha30/react-test npm test

      - name: Generate Deployment package
        run: zip -r deploy.zip . -x '*.git'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: "docker-react-poc"
          environment_name: "Dockerreactpoc-env"
          version_label: "1.0.0"
          region: ap-south-1
          deployment_package: deploy.zip
